export const FETCH_JOKES = 'FETCH_JOKES';
export const FETCH_JOKES_FAIL = 'FETCH_JOKES';
export const FETCH_JOKES_REJECT = 'FETCH_JOKES';
export const FETCH_CACHED_JOKES = 'FETCH_CACHED_JOKES';
export const FETCH_CACHED_JOKES_FAIL = 'FETCH_CACHED_JOKES';